main: pk.guimx.PokiSense
version: 1.2.0
name: PokiSense
author: guimx
api-version: 1.8.8
commands:
  headed:
    description: 'big headed fan!!!'
  fly:
    description: 'makes you explode'
  speed:
    description: 'mario kart'
  connect:
    description: '¯\_(ツ)_/¯'
  glow:
      description: 'brillo'
  cglow:
    description: 'glowv2'
  staff:
    description: 'askdjgasyudg812o'
  panic:
    description: 'PANIC!!!!'
  block:
    description: 'asdjlhaskjld'
  kb:
    description: 'ziblacking'